use_frameworks!

platform :ios, '9.3'

project 'BlueBillywigPlayerSDK.xcodeproj'
project 'BlueBillywigPlayerSDK-xcode-12.xcodeproj'

target :BlueBillywigPlayerSDK_Example do
  project 'BlueBillywigPlayerSDK'
  pod 'BlueBillywigPlayerSDKPreXCode11', :path => '../'
  workspace 'BlueBillywigPlayerSDK.xcworkspace'
end

target :BlueBillywigPlayerSDK_Example_xcode_12 do
  project 'BlueBillywigPlayerSDK-xcode-12.xcodeproj'
  pod 'BlueBillywigPlayerSDKPreXCode11', :path => '../'
  workspace 'BlueBillywigPlayerSDK-xcode-12.xcworkspace'
end
